"""
agent.py
========
LangGraph multi-agent pipeline that turns a ThreatSense detection into a
fully structured SOC incident report.

Pipeline (3 nodes)
------------------
  detection dict
       │
       ▼
  [triage]  ── summarises the raw detection, decides severity
       │
       ▼
  [enrich]  ── attaches MITRE ATT&CK techniques + SHAP indicators
       │
       ▼
  [report]  ── Groq Llama 3.1 drafts the full incident report
       │
       ▼
  incident report dict

LLM
---
  Provider : Groq (free tier)
  Model    : llama-3.1-70b-versatile
  Fallback : if Groq is unavailable, the pipeline still returns the
             structured (non-LLM) parts so nothing crashes.

Setup
-----
  1. Add GROQ_API_KEY=gsk_... to your .env file.
  2. pip install langchain-groq

Run (standalone test)
---------------------
  python -m src.agent
"""

from __future__ import annotations

import json
import logging
import os
import uuid
from datetime import datetime, timezone
from typing import Optional, TypedDict

from dotenv import load_dotenv
from langgraph.graph import END, START, StateGraph

from src.mitre_mapper import get_mitre_info, get_severity

load_dotenv()

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
)
logger = logging.getLogger("threatsense.agent")


# ---------------------------------------------------------------------------
# LLM initialisation
# ---------------------------------------------------------------------------

def _build_llm():
    """Initialise the Groq LLM client.

    Returns:
        A LangChain ChatGroq instance, or None if the key is missing
        (fallback mode — structured report still generated without AI text).
    """
    api_key = os.getenv("GROQ_API_KEY", "").strip()
    if not api_key:
        logger.warning(
            "GROQ_API_KEY not set. Agent will run in fallback mode "
            "(structured report without AI narrative)."
        )
        return None
    try:
        from langchain_groq import ChatGroq
        llm = ChatGroq(
            model="llama-3.1-70b-versatile",
            api_key=api_key,
            temperature=0.2,       # low temp for factual SOC reports
            max_tokens=1024,
        )
        logger.info("Groq LLM initialised (llama-3.1-70b-versatile)")
        return llm
    except Exception as exc:
        logger.error("Failed to initialise Groq LLM: %s", exc)
        return None


LLM = _build_llm()


# ---------------------------------------------------------------------------
# Agent state
# ---------------------------------------------------------------------------

class ThreatSenseState(TypedDict):
    """Shared state passed between all agent nodes.

    Attributes:
        detection:        Raw detection dict from the inference pipeline.
        incident_id:      Unique ID generated at triage time.
        timestamp:        ISO-8601 UTC timestamp of the incident.
        triage_summary:   Plain-English summary produced by the triage node.
        severity:         Severity level: Critical / High / Medium / Low / None.
        mitre_techniques: List of MITRE ATT&CK technique dicts from the mapper.
        top_indicators:   Top SHAP features formatted as indicator strings.
        ai_analysis:      Full narrative generated by the Groq LLM.
        recommended_actions: List of concrete response actions.
        incident_report:  Final assembled report dict (set by report node).
        error:            Error message if any node fails (None = all good).
    """
    detection: dict
    incident_id: str
    timestamp: str
    triage_summary: str
    severity: str
    mitre_techniques: list[dict]
    top_indicators: list[str]
    ai_analysis: str
    recommended_actions: list[str]
    incident_report: dict
    error: Optional[str]


# ---------------------------------------------------------------------------
# Node 1 — Triage
# ---------------------------------------------------------------------------

def triage_node(state: ThreatSenseState) -> dict:
    """Summarise the raw detection and assign an incident ID + timestamp.

    This node does not call the LLM — it uses deterministic logic so it
    always succeeds even in fallback mode.

    Args:
        state: Current agent state (only 'detection' is populated).

    Returns:
        Partial state update: incident_id, timestamp, triage_summary,
        severity, error.
    """
    try:
        det = state["detection"]
        threat_class  = det.get("predicted_class", "Unknown")
        anomaly_score = det.get("anomaly_score", 0.0)
        confidence    = max(det.get("class_probabilities", {}).values(), default=0.0)

        incident_id = f"INC-{uuid.uuid4().hex[:8].upper()}"
        timestamp   = datetime.now(timezone.utc).isoformat()
        severity    = get_severity(threat_class)

        triage_summary = (
            f"Network flow classified as '{threat_class}' with "
            f"{confidence:.1%} confidence. "
            f"Anomaly score: {anomaly_score:.4f} "
            f"({'anomalous' if anomaly_score < 0 else 'normal range'}). "
            f"Severity: {severity}."
        )

        logger.info("[triage] %s  class=%s  severity=%s", incident_id, threat_class, severity)
        return {
            "incident_id":    incident_id,
            "timestamp":      timestamp,
            "triage_summary": triage_summary,
            "severity":       severity,
            "error":          None,
        }
    except Exception as exc:
        logger.error("[triage] failed: %s", exc)
        return {"error": str(exc)}


# ---------------------------------------------------------------------------
# Node 2 — Enrich
# ---------------------------------------------------------------------------

def enrich_node(state: ThreatSenseState) -> dict:
    """Attach MITRE ATT&CK techniques and format SHAP indicators.

    Args:
        state: Current agent state (triage fields populated).

    Returns:
        Partial state update: mitre_techniques, top_indicators.
    """
    try:
        det          = state["detection"]
        threat_class = det.get("predicted_class", "Unknown")

        # MITRE ATT&CK mapping
        try:
            mitre_techniques = get_mitre_info(threat_class)
        except ValueError:
            mitre_techniques = []
            logger.warning("[enrich] No MITRE mapping for class '%s'", threat_class)

        # Format top SHAP features as human-readable indicators
        shap_features = det.get("top_shap_features", [])
        top_indicators = [
            f"{f['feature']} = {f['value']:.4f}  (impact: {f['shap_value']:+.4f})"
            for f in shap_features[:5]   # top 5 only
        ]

        logger.info(
            "[enrich] attached %d MITRE techniques, %d indicators",
            len(mitre_techniques), len(top_indicators),
        )
        return {
            "mitre_techniques": mitre_techniques,
            "top_indicators":   top_indicators,
        }
    except Exception as exc:
        logger.error("[enrich] failed: %s", exc)
        return {"error": str(exc), "mitre_techniques": [], "top_indicators": []}


# ---------------------------------------------------------------------------
# Node 3 — Report writer
# ---------------------------------------------------------------------------

_REPORT_PROMPT = """\
You are a senior SOC analyst writing a concise incident report.

DETECTION SUMMARY
-----------------
Threat class    : {threat_class}
Severity        : {severity}
Anomaly score   : {anomaly_score:.4f}
Confidence      : {confidence:.1%}
Timestamp       : {timestamp}

MITRE ATT&CK TECHNIQUES
-----------------------
{mitre_block}

TOP NETWORK INDICATORS
----------------------
{indicators_block}

TRIAGE NOTES
------------
{triage_summary}

Write a structured SOC incident report. Return ONLY valid JSON with these
exact keys — no markdown, no code fences, no extra text:

{{
  "executive_summary": "2-3 sentence overview for management",
  "threat_analysis": "3-4 sentence technical analysis of what happened",
  "recommended_actions": [
    "Action 1",
    "Action 2",
    "Action 3",
    "Action 4"
  ],
  "investigation_notes": "1-2 sentences on what a SOC analyst should look at next"
}}
"""


def _fallback_report(state: ThreatSenseState) -> dict:
    """Generate a minimal report without LLM when Groq is unavailable."""
    threat_class = state["detection"].get("predicted_class", "Unknown")
    severity     = state.get("severity", "Unknown")
    actions_map  = {
        "DoS":         ["Block source IPs at perimeter firewall",
                        "Enable rate limiting on affected services",
                        "Notify upstream ISP if volumetric attack",
                        "Activate DDoS mitigation appliance"],
        "PortScan":    ["Block scanning host at firewall",
                        "Review firewall rules for exposed services",
                        "Check for follow-up exploitation attempts",
                        "Log and monitor the source IP for 48 hours"],
        "Brute Force": ["Lock accounts after failed login threshold",
                        "Block source IP at firewall",
                        "Enable MFA on affected services immediately",
                        "Audit authentication logs for successful logins"],
        "Bot":         ["Isolate infected host from network",
                        "Block C2 domains/IPs at DNS and firewall",
                        "Run endpoint malware scan",
                        "Reset credentials on affected host"],
        "Benign":      ["No action required — flow is benign"],
    }
    return {
        "executive_summary": (
            f"A {threat_class} threat was detected with severity {severity}. "
            "Automated analysis has been completed. Manual review recommended."
        ),
        "threat_analysis": (
            f"The network flow was classified as {threat_class} by the "
            "ThreatSense ML pipeline. MITRE ATT&CK techniques have been "
            "mapped. SHAP feature analysis indicates the key contributing "
            "network flow characteristics."
        ),
        "recommended_actions": actions_map.get(threat_class, ["Review incident manually"]),
        "investigation_notes": (
            "Review the top network indicators and cross-reference with "
            "firewall and endpoint logs for the same time window."
        ),
    }


def report_node(state: ThreatSenseState) -> dict:
    """Generate the full SOC incident report using Groq Llama 3.1.

    Falls back to a structured template if the LLM is unavailable or
    returns malformed JSON.

    Args:
        state: Current agent state (triage + enrich fields populated).

    Returns:
        Partial state update: ai_analysis, recommended_actions,
        incident_report.
    """
    try:
        det          = state["detection"]
        threat_class = det.get("predicted_class", "Unknown")
        anomaly_score= det.get("anomaly_score", 0.0)
        confidence   = max(det.get("class_probabilities", {}).values(), default=0.0)

        # Format MITRE block for the prompt
        mitre_techniques = state.get("mitre_techniques", [])
        if mitre_techniques:
            mitre_block = "\n".join(
                f"  • {t['technique_id']} — {t['technique_name']} ({t['tactic']})"
                for t in mitre_techniques
            )
        else:
            mitre_block = "  No techniques mapped (Benign traffic)"

        indicators_block = "\n".join(
            f"  • {ind}" for ind in state.get("top_indicators", [])
        ) or "  No SHAP indicators available"

        # Try LLM first, fall back to template
        llm_content = None
        if LLM is not None:
            prompt = _REPORT_PROMPT.format(
                threat_class=threat_class,
                severity=state.get("severity", "Unknown"),
                anomaly_score=anomaly_score,
                confidence=confidence,
                timestamp=state.get("timestamp", ""),
                mitre_block=mitre_block,
                indicators_block=indicators_block,
                triage_summary=state.get("triage_summary", ""),
            )
            try:
                response = LLM.invoke(prompt)
                raw_text = response.content.strip()
                # Strip any accidental markdown fences
                raw_text = raw_text.replace("```json", "").replace("```", "").strip()
                llm_content = json.loads(raw_text)
                logger.info("[report] LLM report generated successfully")
            except json.JSONDecodeError as exc:
                logger.warning("[report] LLM returned invalid JSON (%s), using fallback", exc)
            except Exception as exc:
                logger.warning("[report] LLM call failed (%s), using fallback", exc)

        content = llm_content if llm_content else _fallback_report(state)

        # Assemble the final incident report
        incident_report = {
            "incident_id":        state.get("incident_id", f"INC-{uuid.uuid4().hex[:8].upper()}"),
            "timestamp":          state.get("timestamp", datetime.now(timezone.utc).isoformat()),
            "threat_class":       threat_class,
            "severity":           state.get("severity", "Unknown"),
            "anomaly_score":      anomaly_score,
            "confidence":         round(confidence, 4),
            "triage_summary":     state.get("triage_summary", ""),
            "mitre_techniques":   mitre_techniques,
            "top_indicators":     state.get("top_indicators", []),
            "executive_summary":  content.get("executive_summary", ""),
            "threat_analysis":    content.get("threat_analysis", ""),
            "recommended_actions":content.get("recommended_actions", []),
            "investigation_notes":content.get("investigation_notes", ""),
            "generated_by":       "groq/llama-3.1-70b-versatile" if llm_content else "fallback-template",
        }

        logger.info(
            "[report] incident report assembled  id=%s  class=%s",
            incident_report["incident_id"], threat_class,
        )
        return {
            "ai_analysis":        content.get("threat_analysis", ""),
            "recommended_actions":content.get("recommended_actions", []),
            "incident_report":    incident_report,
        }
    except Exception as exc:
        logger.error("[report] failed: %s", exc)
        return {"error": str(exc), "incident_report": {}}


# ---------------------------------------------------------------------------
# Build graph
# ---------------------------------------------------------------------------

def build_agent() -> object:
    """Build and compile the ThreatSense LangGraph agent.

    Returns:
        Compiled LangGraph runnable. Call .invoke({"detection": ...}) to run.
    """
    graph = StateGraph(ThreatSenseState)

    graph.add_node("triage", triage_node)
    graph.add_node("enrich", enrich_node)
    graph.add_node("report", report_node)

    graph.add_edge(START,    "triage")
    graph.add_edge("triage", "enrich")
    graph.add_edge("enrich", "report")
    graph.add_edge("report", END)

    return graph.compile()


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

# Module-level compiled agent (reused across calls)
_AGENT = None


def generate_incident_report(detection: dict) -> dict:
    """Generate a SOC incident report from a ThreatSense detection.

    This is the main entry point used by the FastAPI backend.

    Args:
        detection: Detection dict from the inference pipeline, containing:
            - predicted_class (str)
            - anomaly_score (float)
            - class_probabilities (dict)
            - top_shap_features (list of dicts with 'feature', 'value', 'shap_value')

    Returns:
        Incident report dict with keys: incident_id, timestamp, threat_class,
        severity, anomaly_score, confidence, triage_summary, mitre_techniques,
        top_indicators, executive_summary, threat_analysis,
        recommended_actions, investigation_notes, generated_by.
    """
    global _AGENT
    if _AGENT is None:
        _AGENT = build_agent()

    result = _AGENT.invoke({"detection": detection})
    return result.get("incident_report", {})


# ---------------------------------------------------------------------------
# Standalone test
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    # Synthetic detection — mimics output from inference.py (Phase 5)
    sample_detection = {
        "predicted_class": "DoS",
        "anomaly_score": -0.1523,
        "class_probabilities": {
            "Benign": 0.02,
            "DoS": 0.94,
            "PortScan": 0.01,
            "Brute Force": 0.02,
            "Bot": 0.01,
        },
        "top_shap_features": [
            {"feature": "Flow Duration",      "value": 0.0002,   "shap_value": 2.341},
            {"feature": "Total Fwd Packets",  "value": 1.0,      "shap_value": 1.872},
            {"feature": "Flow Bytes/s",       "value": 984231.0, "shap_value": 1.654},
            {"feature": "Destination Port",   "value": 80.0,     "shap_value": -0.932},
            {"feature": "Flow Packets/s",     "value": 5000.0,   "shap_value": 0.821},
        ],
    }

    print("\n" + "="*60)
    print("ThreatSense — Generating incident report ...")
    print("="*60)
    report = generate_incident_report(sample_detection)
    print(json.dumps(report, indent=2))
